dpi-aware=yes
font=ZedMono Nerd Font:size=14
width=50
; layer=overlay
; exit-on-keyboard-focus-loss=no
horizontal-pad=16
inner-pad=8
; fields=filename,name
icons-enabled=no


[colors]
background=2e3440ff

selection=3b4252ff

selection-text=eceff4ff

match=81a1c1ff
selection-match=81a1c1ff
border=81a1c1ff

input=616e88ff
prompt=616e88ff
text=616e88ff

[border]
width=1
radius=0
